### ISSUE TITLE
Couple of issues i noted with helium 3

### ISSUE THREAD

**Issue by sojan-official** [slashlos/Helium#10]
- doesn't helium 3 support the keyboard shortcut to toggle between translucent mode? 
- in the translucent mode, the auto-hide title bar option still work, causing a jump while the mouse passes over

**Comment by slashlos** [comment]
Whey yes it does support keyboard shortcuts, but Helium of course needs to be the current app or key window.

The window isn't moved just the title toggles but the video affect - jump, I've noticed.  There is a "leak" where by leaving the window via the title bar leaves the bar on.  

We're not "release" yet but going forward please note osx and Helium versions, thanks!

**Comment by sojan-official** [comment]
so helium 2 had an option ( cmd + t ) to switch between the translucent mode and normal mode 
i couldn't get it working in 3

build 2773
macos 10.14 beta

**Comment by slashlos** [comment]
Ah, that's for keeping me honest; I meant to restore it.  

When Helium went to multi-window I wanted to simplify the UI, so I had added an always state vs never, as outside is vs over for mouse movements.   Pressing %T will toggle between states:
<img width="170" alt="screen shot 2018-08-14 at 12 03 32 pm" src="https://user-images.githubusercontent.com/3155005/44103622-b925e8e4-9fba-11e8-9ac7-30586cdb8b76.png"> 

This shows that Mouse Over is latent but currently not enabled; pressing %T yields:

<img width="170" alt="screen shot 2018-08-14 at 12 10 49 pm" src="https://user-images.githubusercontent.com/3155005/44103792-228356b4-9fbb-11e8-8324-a5c687fde076.png">
This posting restores %T toggle:
[Helium 2018-08-14 12-13-52.zip](https://github.com/slashlos/Helium/files/2287699/Helium.2018-08-14.12-13-52.zip) in version 3.0.2912 and beyond; artwork, help text etc yet to be updated though.
