### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by orditeck** [slashlos/Helium#12]
@slashlos could you please publish a [downloadable release](https://github.com/slashlos/Helium/releases) in your repo (.zip containing the compiled app)? 😄

**Comment by orditeck** [comment]
Ah, well, I guess I'm asking the same as https://github.com/slashlos/Helium/issues/3. Any update on this then?

**Comment by slashlos** [comment]
p.s., the web page .zip is just the repo so please take the .pkg from xcode .zip I note in this issue.

Release 3.0.3502 [Helium 2018-09-25 21-21-13.zip](https://github.com/slashlos/Helium/files/2422240/Helium.2018-09-25.21-21-13.zip)

**Comment by slashlos** [comment]
Done!  thanks for pointing out the obvious.

**Comment by orditeck** [comment]
Awesome, thanks!

**Comment by orditeck** [comment]
Btw if you ever want to make "drag&drop" dmg files, take a look here: 
https://github.com/LinusU/node-appdmg

**Comment by slashlos** [comment]
I might just do that; the Release portal for non-dev is confusing so perhaps I can script this once I validate / export from Xcode.  Thanks for pointer.
