### ISSUE TITLE
macOS Mojave 

### ISSUE THREAD

**Issue by irmantas** [slashlos/Helium#14]
Hi,

I'm trying latest pre-release version (Helium 3.0.3599), but is seems it does not work at all when i try to  load twitch stream it just shows OFFLINE. When I try load youtube it shows "An error occurred. Please try again later. (Playback ID: 0yiWg1SOq4pfSPOz)".

Where could be a problem?
Previously I tried original Helium, but it does not support twitch.

**Comment by slashlos** [comment]
I'm not familiar with the stream but what URL or otherwise reproducing steps can I test with ?

**Comment by irmantas** [comment]
Hi, thanks for response. I made short [video](https://www.youtube.com/watch?v=X9Zr9WD8PdY), hope it helps.

**Comment by irmantas** [comment]
Thanks for response, currently I am using Mojave Beta.
In case of Youtube I just opened random regular video from my homepage.

**Comment by slashlos** [comment]
Well it seems to be working on 10.12 and 10.13; thanks for brining twhich.tv to my attention - it looks interesting.

**Comment by slashlos** [comment]
So I upgrade a host to Mojave - ugh.  The url - http[s]://twhich.tv appears unregistered now.

**Comment by slashlos** [comment]
Huh, now site is there - twhich.tv ?  

Anyway from Safari use share button and Open in Helium but I get a dark window with OFFLINE in top right?

So in a Helium window, I CTRL/click to Open URL - twhich.tv - I captured this [video](https://youtu.be/kIa2KgvFe2k)

I guess there's something missing in the handoff but direct access from Helium 3 seems ok?

**Comment by kotakerdus** [comment]
twitch.tv I believe?
It is some kind of live streaming services mostly used for live gaming streaming

For youtube when I turned off the Magic URL redirect it is working but it loads everything on Youtube just like normal web browser, it seems that Youtube won't allow unrecognised app/system to load its video, or is it the new Mojave that breaks the video?

Btw, thanks for your work, love all the improvements :D

**Comment by slashlos** [comment]
It could be Mojave or utube;  more to test. Thanks for the info. 
—
/los "I was a teenage net random"

**Comment by OJ7** [comment]
I've also had trouble with Twitch not loading properly but if I disable "Magic URL Redirects" I can get it to work fine and play video by going into "Theatre Mode"
