### ISSUE TITLE
Can the key to quit (ESC) be customizable

### ISSUE THREAD

**Issue by ssetti** [slashlos/Helium#20]
Currently ESC closes the window

**Comment by slashlos** [comment]
Technically yes, but I think, feel that's a departure from typical usage.  I was actually thinking of removing it as CMD-W is the norm, but keeping it for return from full-screen mode.

**Comment by ssetti** [comment]
That will be awesome… thanks for the speedy response

**Comment by slashlos** [comment]
As described so eloquently [here](https://stackoverflow.com/a/42440020/564870). the CMD. or ESCape keys follow a Macintosh design, and as I said earlier I'd rather not diverge the behavior but perhaps maybe provide a means ignore / disable it ?
