### ISSUE TITLE
Doesn't stay on top of Keynote presentation

### ISSUE THREAD

**Issue by charwick** [slashlos/Helium#21]
First of all thanks for picking this project back up. My use case for this project would be to keep a webpage in the foreground on the presenter's screen during a Keynote presentation. Unfortunately Helium gets covered up by Keynote. Is it possible to force the window in front?

**Comment by slashlos** [comment]
Is this when you have a full screen keynote slide show going ?  

If so, then like when any app is full screen I doubt you can get another to occlude it.  Yes, others have used java bits to hack about toggling the app dock visibility - which I'm not 100% is a solution - see this [link.](https://github.com/electron/electron/issues/10078).

About the best I think you can do is either use multiple screens or view the slide as single window - without the inspector (side) view.

I'm still investing and I'd be happy to be proven wrong ;-)

**Comment by charwick** [comment]
I don't know the technical details, but it doesn't seem like presentation mode is using the same API as regular fullscreen mode, since it's not creating a new Space. Not sure how much of a difference that makes.

**Comment by slashlos** [comment]
Pretty good guess - I suspect something?  I can appreciate the benefit of having an extra window, I presume to show in real-time something to the audience.  I wasn't following the conversation in the link just why hiding the dock would affect the occlusion but that seemed to be java solution and wasn't clear to me a keynote style environment would work; but I'll tinker a bit if I can figure out something.

**Comment by slashlos** [comment]
Ha, Helium floats over Powerpoint quite nicely.

**Comment by charwick** [comment]
Ah, I'd hate to have to convert to Powerpoint for this! For me, I'd be putting it over the presenter window; ideally I'd like to have sli.do open on my screen in order to address questions as they come in.

**Comment by creolis** [comment]
Another guy in need here ;) 
I'd need it to display real time information to the audience during a keynote presentation,
it would be great to have Helium working with Keynote

**Comment by slashlos** [comment]
Found a solution; try build [5711](https://github.com/slashlos/Helium/releases/tag/3.0.5711) from releases page.
