### ISSUE TITLE
Unsupported browser- hulu

### ISSUE THREAD

**Issue by k-christensen** [slashlos/Helium#24]
When I try to watch a video on hulu, I get an error message that I have an unsupported browser. I checked and my version of safari can play hulu videos, as can chrome. Is there any way to update the browser in helium?

**Comment by k-christensen** [comment]
Nevermind, changed the user agent and works fine now

**Comment by slashlos** [comment]
To what?

**Comment by k-christensen** [comment]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Comment by slashlos** [comment]
Awesome; that addressed a NetFlix and GitHub issue I was having, but Hulu still complains - P-DEV302, and its "We're having trouble playing this" page link to visit is not found :-(
