### ISSUE TITLE
Doesn't stay above full screen applications anymore

### ISSUE THREAD

**Issue by franknavarro** [slashlos/Helium#26]
This feature was working in the previous version `Version 3.0.4125` but I replaced Helium with the newest version on the releases pages `Version 3.0.4162` and now Helium windows cannot be dragged over full screen applications.

I have a multiple monitor set up. If I start helium on monitor 1 and on monitor 2 I have an application in full screen mode and I try to drag helium over from monitor 1 to 2 the application stops dragging right on the threshold of when the cursor crosses the boundary of monitor 1.

If I open helium and the open another application on the same screen then helium will hover over the other app, however one I put that app into full screen mode helium becomes hidden.

Again all of this was working in the previous version that is listed on the releases pages for this project, `Version 3.0.4125`, but the most recent version `Version 3.0.4162` seems to have broken this feature.

**Comment by slashlos** [comment]
Thank you but I cannot reproduce.

I’m using PowerPoint on my #2 (A1407 27”) in slide show mode; I drag a Helium from #1 (also A1407) to #2 ok;  then on #2, create new Helium and drag that back to #1. 

Maybe, maybe a prefs issue so I would verify them; if you like you can clear all - hold down Shift+Option but this will clear *all*; you can restore individual playlist by creating new, rename to an old name, then press Revert then Save for each. 

I’m on OS X 10.14.6; can you tell me the other app?

**Comment by slashlos** [comment]
p.s. is this a playlist panel?  If so yes I broke something and fixed; expect upload later today.

**Comment by s3lia** [comment]
Hello slashlos,

First of all, thank you for reviving this project and providing updates so frequently.

Unfortunately, I have the same issue as franknavarro. Helium 3 will work perfectly until you switch to a space with a fullscreen app. It’s not just specific apps but as far as I can tell all of them. 

I recorded a short video for demonstration.

https://streamable.com/krt7z

Helium 3.0.4162 
macOs Mojave 10.14.6

**Comment by slashlos** [comment]
Hmm; can you try and toggle OFF then ON the attribute (pre-view/window) `Float Above All Spaces`

**Comment by slashlos** [comment]
[franknavarro](https://github.com/franknavarro) I suspect your pref might be confused; recently I had shuffled some prefs to be window specific while others global affecting new windows. UA is one such pref.

**Comment by franknavarro** [comment]
@slashlos Unfortunately toggling the `Float Above All Spaces` did not seem to fix the issue for me. 

I tried toggling it off and then back on while right clicking on the window and navigating to `Appearance -> Float Above All Spaces` and also through the top bar menu by navigating to `Window -> Appearance -> Float Above All Spaces`. Neither seemed to work.

**Comment by slashlos** [comment]
Still think it's a pref issue - some have been moved to be document specific, others global.  To initialize prefs, start Helium holding down SHIFT+OPTION; you'll get a audible feedback it was done.  

As for full screen apps hiding Helium (4162), trying the [Finder on my 2nd monitor(https://youtu.be/rkys1n52Dk0) works just fine. I hope to quiet down any pref changes.

**Comment by franknavarro** [comment]
This issue has been fixed with the most recent release of `Helium 3.0.4798`
