### ISSUE TITLE
Binary download?

### ISSUE THREAD

**Issue by xenio** [slashlos/Helium#3]
Is there a binary download available? Or I have to compile by myself?
Thank you for your work on Helium 👍

**Comment by slashlos** [comment]
The last working binary is pre-sandbox which you could build.  Supporting the app store is really the only avenue for the binary from me given the potential for mischief out there.  I've had to file a ticket with Apple re: WKWebView and its sandbox support which I hope they'll address soon!

**Comment by slashlos** [comment]
https://github.com/slashlos/Helium/files/1639956/Helium.zip has such a download given the issue re: sandbox and High Sierra certification imposed on us.  This build was the last reviewed but not approved given these issues.  Still working towards a resolution though.
