### ISSUE TITLE
Google Meet doesn't work

### ISSUE THREAD

**Issue by mmorearty** [slashlos/Helium#33]
There is probably nothing you can do this, but I'll log it just in case: Google Meet doesn't work. It works in regular Safari, but not in Helium 3.

To reproduce, go to https://meet.google.com, log into your Google account, and try to start a meeting. It hangs at the following screen:

<img width="751" alt="Screen Shot 2020-04-16 at 9 32 59 AM" src="https://user-images.githubusercontent.com/207671/79482361-9a2ac300-7fc5-11ea-9e48-51046dea782d.png">

**Comment by slashlos** [comment]
What version, os, etc?  You might need to update the user agent string; suggest Safari's current; then I get 

![ Shapshot at 2020-04-19 at 08 03 37](https://user-images.githubusercontent.com/3155005/79687289-4eba2400-8214-11ea-8848-43ff83260535.png)

**Comment by mmorearty** [comment]
Ah, sorry I was so vague.

Helium: Current version (just downloaded "Helium 3" from the App Store)
macOS: Catalina 10.15.4 (19E287)
Safari: Version 13.1 (15609.1.20.111.8)

User agent from Helium:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15
```

User agent from Safari:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
```

My Google accounts are different from yours — they have a button that says "Join or start a meeting," and I can use that to start a new meeting. Both of them are G Suite accounts — one for my job and another for my personal domain — so that may be the difference. It is _after_ clicking that button, and then clicking "Continue" on the next screen, that the hang happens. I tried changing the user agent to match the one from Safari; that didn't help.

**Comment by slashlos** [comment]
If you had installed H3 before, it might be restoring that earlier UA setting. Verify by going to the 'what's my user agent' web search. H3 is probably not interacting as a real web browser but will hopefully; you might be able to establish via safari then share to H3?

**Comment by manspeterson** [comment]
My guess it has to do with it now showing the prompts for allowing camera and microphone. Doesn't work for any video call services that I've tried. Would really love this feature!

**Comment by slashlos** [comment]
No worries mate; with the Jaden's return? I've moved to this works successor - [He3](https://github.com/slashlos/He3) which will be available on the Apple App Store, gratis.  if you could please file this item there so I won't lose track of it, thank you.
