### ISSUE TITLE
Could you rename the app on the Mac App Store and use a different icon?

### ISSUE THREAD

**Issue by JadenGeller** [slashlos/Helium#34]
I haven't kept Helium up-to-date, so I'm glad you were able to fork it and make all these great improvements! Could you please use a different name though to avoid confusion between your app and my app? I obviously don't mind that you built off the concept or code (yay, MIT license 😄), but I would prefer if you chose a different name for your app.

Hope you understand where I'm coming from, and thank you!

**Comment by slashlos** [comment]
Hey, hey, glad you're back and hope all's well.  It's Helium 3, and it's icon is also diverged. I plan to update other artwork in a subtle but distinctive way.

**Comment by JadenGeller** [comment]
Thank you! I'm doing alright 😄

I think reusing the name Helium is still really confusing, even with the 3. Could you find a name the doesn't use "Helium" in it at all? I can help brainstorm some ideas if that's useful!

**Comment by slashlos** [comment]
Yes I agree but then draw a blank; you know there are several other app with helium in their name; 

however I did want to maintain the context as at the time I was didn’t know what your plans are.  

H3 is quite a different beast now, never meant this to be a ‘gig’ but a diversion, and I’m wanting to get back to other projects

Anyway, back to sewing masks - I give them away to fiends & family.

And take care out there “among the English”.

**Comment by JadenGeller** [comment]
Your app is the only I know of on the App Store with the same exact name (with a different version number). Could you rename the app to something different, like “Neon”, “Float”, “BrowserOnTop”, “Balloon: Floating Web Browser”, “Hover”, “Picture-In-Picture Browser”, “Hot Air”, or something else?

**Comment by slashlos** [comment]
HA you. Should look at the iOS side re name collisions. But, no worries have a name picked out.

**Comment by JadenGeller** [comment]
Are you still planning to rename the app on the App Store?

**Comment by slashlos** [comment]
Yes it’s being rebranded with shiny new name and artwork. It’s decoupled from my earlier fork.
