### ISSUE TITLE
Snapshot shortcut does not work as expected

### ISSUE THREAD

**Issue by bweinand** [slashlos/Helium#36]
Snapshot All should be triggered on Option+Command+Y. But in fact it is triggered on Option+Command alone. Using any Option+Command shortcut in any other application results in a snapshot and fills up the disk.

**Comment by slashlos** [comment]
Thanks for the notice; there was a bug re: global key monitor fixed; this happened as I was transitioning to [He3](https://github.com/slashlos/He3) as its rebranding on the App Store, in final edits for submission.
