### ISSUE TITLE
Switch tabs shortcut?

### ISSUE THREAD

**Issue by mboevink** [slashlos/Helium#41]
Is there anyway to quickly shift between tabs via a shortcut? If not, can you please add ctrl+tab like Chrome?

**Comment by slashlos** [comment]
So CTRL+TAB => NEXT_TAB,  and SHIFT+CTRL+TAB => PREV_TAB ?

**Comment by mboevink** [comment]
Yes that would be excellent. Thank you.

**Comment by slashlos** [comment]
Ah, btw this work is superseded by He3 on the app store:

![Screen Shot 2020-11-15 at 6 50 53 PM](https://user-images.githubusercontent.com/3155005/99200486-98032f80-2773-11eb-9f73-d974c75f7881.png)

hidden menu items - simple CTRL-RIGHT and CTRL-LEFT, no shift; I'm working to post a localization update (de, es, fr, it) this week.

**Comment by mboevink** [comment]
Cheers that's done it. Probably should have guessed that one.
