### ISSUE TITLE
"This video format is not supported." - Google Play Movies

### ISSUE THREAD

**Issue by wohfab** [slashlos/Helium#42]
Using [Google Play Movies](https://play.google.com/movies), I get the `This video format is not supported.` error. 

- macOS Big Sur 11.1
- Helium 2.0

**Comment by slashlos** [comment]
Helium 2 and 3 were superseded by [He3](https://github.com/slashlos/He3).

So, this should be entered into He3's issues [page.](https://github.com/slashlos/He3/issues)
