### ISSUE TITLE
Option to disable keyboard shortcuts

### ISSUE THREAD

**Issue by jhonatn** [slashlos/Helium#44]
Currently, a keyboard shortcut is conflicting with Xcode (Cmd + Ctrl + Opt). I'm not using He3's shortcut, so it would be useful to disable it.

**Comment by slashlos** [comment]
Helium was replaced by He3 on the app store, but I think you're referring to the QQ (quick quiet) sequence which was altered.  Please move to He3, also on GitHub.

**Comment by jhonatn** [comment]
I was talking about He3, yes. That said, I didn't know He3 was being developed in a different repo. Should this repo README indicate where to find the new repo?
