### ISSUE TITLE
Menubar icon shows even with preference set to disable

### ISSUE THREAD

**Issue by edrozenberg** [slashlos/Helium#9]
After restarting the app, even though "Disable menubar icon" is set in prefs, the colorful menubar icon still shows.

Workaround after each app launch: set the disable menubar icon pref to off then back to on.

**Comment by slashlos** [comment]
Ah yes, on my todo; there isn't a hidden binding to the app needs to do this manually; Fixed in 3.0.2024 (and beyond).
